services:
  webapp:
    container_name: mytesttask
    build:
      context: .
      dockerfile: MyTestTask/Dockerfile
    ports:
      - "9999:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=Temp;Username=postgres;Password=admin
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_cont
    image: postgres:latest
    environment:
      POSTGRES_DB: Temp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: